name: GitHub Actions

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code ('${{ github.repository}}' cloned to the runner)
        uses: actions/checkout@v3
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

    
